import { NextResponse } from "next/server";
import { query } from "@/lib/db";
import jwt from "jsonwebtoken";
import { calculateFees, validatePaymentMethod } from "@/lib/paymongo";

export async function POST(req) {
  try {
    // Extract proof if provided
    const { proof, ...rest } = await req.json();
    const {
      user_id,
      amount,
      payment_method
    } = rest;

    // Validate required fields
    if (!user_id || !amount || !payment_method) {
      return NextResponse.json(
        { success: false, message: "Missing required fields" },
        { status: 400 }
      );
    }

    // Validate payment method
    if (!validatePaymentMethod(payment_method)) {
      return NextResponse.json(
        { success: false, message: "Invalid payment method" },
        { status: 400 }
      );
    }

    // Validate amount
    if (amount <= 0) {
      return NextResponse.json(
        { success: false, message: "Amount must be greater than 0" },
        { status: 400 }
      );
    }

    // Calculate fees
    const feeCalculation = calculateFees(amount, payment_method, 'deposit');

    const payment_status = 'pending';
    // Reference number is auto-generated by DB default, but we track ours
    const reference_number = `DEP${Date.now()}${Math.random().toString(36).substr(2, 5).toUpperCase()}`;

    // Save transaction to database
    const insertResult = await query(
      `INSERT INTO transactions (
        user_id,
        type,
        amount,
        fee,
        payment_method,
        reference_number,
        status,
        payment_session_id,
        proof,
        net_amount,
        total_deduction
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id`,
      [
        user_id,
        'deposit',
        amount,
        feeCalculation.fee,
        payment_method,
        reference_number,
        payment_status,
        null,
        proof || null,
        feeCalculation.netAmount,
        feeCalculation.totalAmount
      ]
    );

    return NextResponse.json({
      success: true,
      message: "Deposit created successfully",
      transaction: {
        id: insertResult[0]?.id,
        reference_number,
        amount,
        fee: feeCalculation.fee,
        total_amount: feeCalculation.totalAmount,
        payment_method,
        status: payment_status
      }
    });

  } catch (error) {
    console.error("Deposit API error:", error);
    return NextResponse.json(
      {
        success: false,
        message: error.message || "Server error"
      },
      { status: 500 }
    );
  }
}

export async function GET(req) {
  try {
    const token = req.cookies.get("token")?.value;
    const { searchParams } = new URL(req.url);
    const limit = Math.min(parseInt(searchParams.get("limit") || "50"), 100);
    const offset = parseInt(searchParams.get("offset") || "0");

    if (!token) {
      return NextResponse.json(
        { success: false, message: "Unauthorized" },
        { status: 401 }
      );
    }

    let decoded;
    try {
      decoded = jwt.verify(token, process.env.JWT_SECRET);
    } catch (err) {
      return NextResponse.json(
        { success: false, message: "Invalid token" },
        { status: 401 }
      );
    }

    const userID = decoded.id;

    // Get deposit transactions for the user
    const deposits = await query(
      `SELECT id, amount, fee, payment_method, reference_number,
              status, proof, payment_session_id, created_at
       FROM transactions
       WHERE user_id = $1 AND type = 'deposit'
       ORDER BY created_at DESC
       LIMIT $2 OFFSET $3`,
      [userID, limit, offset]
    );

    // Get total count for pagination
    const totalResult = await query(
      "SELECT COUNT(*) FROM transactions WHERE user_id = $1 AND type = 'deposit'",
      [userID]
    );
    const total = Number(totalResult[0].count);

    return NextResponse.json({
      success: true,
      deposits,
      pagination: { total, limit, offset, hasMore: offset + limit < total }
    });

  } catch (error) {
    console.error("Get deposits error:", error);
    return NextResponse.json(
      { success: false, message: "Server error" },
      { status: 500 }
    );
  }
}
